### ISSUE TITLE
Delete a team/add a team....new team gets last teams points :)

### ISSUE THREAD

**Issue by dookgit** [isislab/CTFd#73]
OK, so if i have 3 teams on the system, and the last team i created have 25 points for a challenge.
If i delete that team, then immediately create a new team....that new team gets the same 25 points and same challenge solve, as the team i deleted.

I guess this is related to teams getting created in order (e.g 1,2,3)...then if i delete team 3, it "frees up" that number for a new team to be created in that spot...but theres already solves against that spot.

:)

Thanks by the way, i love CTFd, planning to use it for a CTF in Australia in 6 weeks time.

**Comment by ColdHeat** [comment]
Hmm. Based off of a thought exercise (no testing), this is maybe b/c sqlite is keeping track of the highest ID to use(?) and solves, wrong keys, and tracking are not being deleted. 

This raises some underlying issues because the question becomes how to delete teams and should they even be deleted or just hidden.

I'm leaning towards deletion of the team because CTFd is designed to have each team have a different name. Just hiding a team would more or less prevent the name from being used. 

I will resolve this later today after some Zzz's and some thought.

**Comment by ColdHeat** [comment]
Having a hard time mentally justifying keeping data for a team that is deleted, especially since a team cannot delete themselves...

**Comment by dookgit** [comment]
I don't want anything keeping for a deleted team.  And it's a rare issue, but thought i'd flag it
